export const GAME_CONSTANTS = {
  MIN_PLAYER_NAME_LENGTH: 1,
  MAX_PLAYER_NAME_LENGTH: 24,
  MIN_TEAM_SIZE: 1,
  MAX_TEAM_SIZE: 5,
  DEFAULT_TEAM_SIZE: 2,
  MIN_SELECT_NUMBER: 1,
  MAX_SELECT_NUMBER: 6,
  ERROR_DISPLAY_DURATION_MS: 5000,
  SOCKET_TIMEOUT_MS: 15000,
} as const;